### ISSUE TITLE
Vault error on login

### ISSUE THREAD

**Issue by amlwwalker** [konomae/lastpass-python#13]
When I run the example script, I get the following back

```
Traceback (most recent call last):
  File "example/example.py", line 18, in <module>
    vault = Vault.open_remote(username, password)
  File "build/bdist.macosx-10.9-x86_64/egg/lastpass/vault.py", line 10, in open_remote
  File "build/bdist.macosx-10.9-x86_64/egg/lastpass/vault.py", line 21, in open
  File "build/bdist.macosx-10.9-x86_64/egg/lastpass/vault.py", line 38, in __init__
  File "build/bdist.macosx-10.9-x86_64/egg/lastpass/parser.py", line 73, in parse_ACCT
  File "build/bdist.macosx-10.9-x86_64/egg/lastpass/parser.py", line 130, in parse_secure_note_server
ValueError: need more than 1 value to unpack
```

Any thoughts as to whats going wrong there?
Thanks
Alex

**Comment by konomae** [comment]
I hope it is fixed in `0.1.3` (#20). Please try version `0.1.3`.
If you still have the same problem please reopen.
