### ISSUE TITLE
Vault login fails

### ISSUE THREAD

**Issue by mattairsorted** [konomae/lastpass-python#16]
I've checked account credentials, multi-factor auth, and everything else I can think of, but receive the following logging output when trying to login via open_remote. Any help appreciated.

INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): lastpass.com
DEBUG:requests.packages.urllib3.connectionpool:"POST /iterations.php HTTP/1.1" 200 None
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): lastpass.com
DEBUG:requests.packages.urllib3.connectionpool:"POST /login.php HTTP/1.1" 200 None
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): lastpass.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /getaccts.php?mobile=1&b64=1&hash=0.0&hasplugin=3.0.23&requestsrc=android HTTP/1.1" 200 None
Traceback (most recent call last):
  File "../bin/airbnb/update_all_calendars.py", line 13, in <module>
    vault = lastpass.Vault.open_remote(lastpass_user, lastpass_pass)
  File "./lastpass/vault.py", line 10, in open_remote
    return cls.open(cls.fetch_blob(username, password, multifactor_password), username, password)
  File "./lastpass/vault.py", line 21, in open
    return cls(blob, blob.encryption_key(username, password))
  File "./lastpass/vault.py", line 45, in __init__
    key = parser.parse_SHAR(i, encryption_key, rsa_private_key)['encryption_key']
  File "./lastpass/parser.py", line 110, in parse_SHAR
    key = decode_hex(rsa_key.decrypt(encrypted_key))
  File "./lastpass/parser.py", line 193, in decode_hex
    return codecs.decode(data, 'hex_codec')
  File "/opt/projects/woop/platform/env/lib64/python2.7/encodings/hex_codec.py", line 42, in hex_decode
    output = binascii.a2b_hex(input)
TypeError: Odd-length string

**Comment by richardhofman6** [comment]
I'm also seeing this issue.

**Comment by rkhwaja** [comment]
I also have this problem - I'm using python 3.6.1. Is anybody successfully using this with python 3? Maybe it's a bytes/unicode problem - after all, this package hasn't been updated in a long time.
Conversely, is anyone successful with python 2?

**Comment by richardhofman6** [comment]
@rkhwaja I have just tested and can confirm that I'm also seeing the same issue using Python 2.7.11.

**Comment by awkwong-whi** [comment]
I see the same error.  I think it occurs on enterprise shared folders.  It works fine for personal accounts.
