### ISSUE TITLE
Error on logging in "ValueError: Input strings must be a multiple of 16 in length"

### ISSUE THREAD

**Issue by keithjjones** [konomae/lastpass-python#21]
I get this error:

```
>>> vault = lastpass.Vault.open_remote('MyUsername', 'MyPassword')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Keith/.virtualenvs/Python3/lib/python3.5/site-packages/lastpass/vault.py", line 10, in open_remote
    return cls.open(cls.fetch_blob(username, password, multifactor_password), username, password)
  File "/Users/Keith/.virtualenvs/Python3/lib/python3.5/site-packages/lastpass/vault.py", line 21, in open
    return cls(blob, blob.encryption_key(username, password))
  File "/Users/Keith/.virtualenvs/Python3/lib/python3.5/site-packages/lastpass/vault.py", line 45, in __init__
    key = parser.parse_SHAR(i, encryption_key, rsa_private_key)['encryption_key']
  File "/Users/Keith/.virtualenvs/Python3/lib/python3.5/site-packages/lastpass/parser.py", line 118, in parse_SHAR
    key = decode_hex(decode_aes256_plain_auto(key, encryption_key))
  File "/Users/Keith/.virtualenvs/Python3/lib/python3.5/site-packages/lastpass/parser.py", line 219, in decode_aes256_plain_auto
    return decode_aes256_ecb_plain(data, encryption_key)
  File "/Users/Keith/.virtualenvs/Python3/lib/python3.5/site-packages/lastpass/parser.py", line 240, in decode_aes256_ecb_plain
    return decode_aes256('ecb', '', data, encryption_key)
  File "/Users/Keith/.virtualenvs/Python3/lib/python3.5/site-packages/lastpass/parser.py", line 288, in decode_aes256
    d = aes.decrypt(data)
  File "/Users/Keith/.virtualenvs/Python3/lib/python3.5/site-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
ValueError: Input strings must be a multiple of 16 in length
```

I use two last pass accounts.  One of my last pass accounts causes this.  My other one works fine.  Any ideas?

**Comment by keithjjones** [comment]
This appears to only be a problem with the current package at PyPi.  If you update the package there with the current code in "master", it should fix this issue and we can close it.

**Comment by konomae** [comment]
@keithjjones Thank you for reporting this! 😃 

I will release new package to PyPi.

**Comment by konomae** [comment]
@keithjjones 
I uploaded a new version `v0.1.1`. Please check it!
