### ISSUE TITLE
Note parsing fails

### ISSUE THREAD

**Issue by pwlmaciejewski** [konomae/lastpass-python#25]
I got the following error on opening valut:

```
Traceback (most recent call last):
  File "./main.py", line 76, in <module>
    deploy(args)
  File "./main.py", line 36, in deploy
    service_deployer.deploy(docker_registry.get_project_image_name(project_config))
  File "./lib/service_deployer.py", line 13, in deploy
    self._fetch_credentials()
  File "./lib/service_deployer.py", line 17, in _fetch_credentials
    self._lastpass.fetch_all_credentials()
  File "./lib/lastpass_client.py", line 34, in fetch_all_credentials
    vault = Vault.open(blob, self._username, self._password)
  File "./venv/lib/python3.6/site-packages/lastpass/vault.py", line 21, in open
    return cls(blob, blob.encryption_key(username, password))
  File "./venv/lib/python3.6/site-packages/lastpass/vault.py", line 38, in __init__
    account = parser.parse_ACCT(i, key)
  File "./venv/lib/python3.6/site-packages/lastpass/parser.py", line 73, in parse_ACCT
    url, username, password = parse_secure_note_server(notes)
  File "./venv/lib/python3.6/site-packages/lastpass/parser.py", line 131, in parse_secure_note_server
    key, value = i.split(b':', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

From what I understand it failed to parse multiline note - when I `print(i.split(b':', 1))` I get something like:

```
[b'Notes', b'* NOTE_TITLE']
[b'NOTE FIRST LINE']
```
It may be relevant that this is an enterprise shared forlder note.

**Comment by konomae** [comment]
I hope it is fixed in #20.
