### ISSUE TITLE
NotImplementedError: Use module Crypto.Cipher.PKCS1_OAEP instead

### ISSUE THREAD

**Issue by thetoolsmith** [konomae/lastpass-python#30]
I used the example in this project and tested with a hardcoded string in my py script, but get this error. I'm running it on a mac OSx.

```
Traceback (most recent call last):
  File "lp.py", line 29, in <module>
    vault = Vault.open_remote(username, password, None, DEVICE_ID)
  File "/Library/Python/2.7/site-packages/lastpass/vault.py", line 12, in open_remote
    return cls.open(blob, username, password)
  File "/Library/Python/2.7/site-packages/lastpass/vault.py", line 23, in open
    return cls(blob, blob.encryption_key(username, password))
  File "/Library/Python/2.7/site-packages/lastpass/vault.py", line 41, in __init__
    self.accounts = self.parse_accounts(chunks, encryption_key)
  File "/Library/Python/2.7/site-packages/lastpass/vault.py", line 62, in parse_accounts
    key = parser.parse_SHAR(i, encryption_key, rsa_private_key)['encryption_key']
  File "/Library/Python/2.7/site-packages/lastpass/parser.py", line 108, in parse_SHAR
    key = decode_hex(rsa_key.decrypt(encrypted_key))
  File "/Library/Python/2.7/site-packages/Crypto/PublicKey/RSA.py", line 375, in decrypt
    raise NotImplementedError("Use module Crypto.Cipher.PKCS1_OAEP instead")
NotImplementedError: Use module Crypto.Cipher.PKCS1_OAEP instead
```

**Comment by konomae** [comment]
Thank you for reporting this!
I uploaded new version `0.3.1`. Please try it.

Fixed this in: https://github.com/konomae/lastpass-python/commit/0998ab6773dc4c8801652d8de50ddfebfede8838

**Comment by thetoolsmith** [comment]
Yes, fixed. Thanks @konomae for responding so quickly and thank you for the tool.
